### ISSUE TITLE
[Suggestion] Add Ext_pipe_tables into yesodDefaultExtensions

### ISSUE THREAD

**Issue by pythonissam** [pbrisbin/yesod-markdown#46]
We often use the pipe markdown to create tables, but it's not in `yesodDefaultExtensions`. I suggest including it into `yesodDefaultExtensions`. What do you think about this?

**Comment by pbrisbin** [comment]
I'd consider this a bug, introduced when we moved to pandoc-2

The options-vs-extensions handling was changed drastically and I didn't give it enough thought when we upgraded. This library's intention was "Pandoc defaults + minor sugar for Yesod" and when moving to pandoc-2 we inadvertently lost a lot of Pandoc's default behavior in this area.

I'm going to change up options-handling generally, and hopefully address these two issues.

**Comment by pbrisbin** [comment]
I've implemented `markdownToHtmlWithExtensions` (#47), which should make it super convenient to use `pandocExtensions` or `githubMarkdownExtensions`, or whatever else you're into.

http://hackage.haskell.org/package/pandoc-2.1.2/docs/Text-Pandoc-Extensions.html

With that in place, I don't know that it'd be super valuable to play whack-a-mole on what the `yesodDefaultExtensions` should be -- I think it's unlikely for me or anyone to have strong opinions on an extension-by-extension basis vs looking for a preset like "GitHub Flavored" or whatever.

I also kind of want to back of off the whole `yesodDefault*` idea anyway, and just use `def`/`def` and leave these new `*With` functions as the primary way for users to get the behavior they want.

Since doing anything in this direction would be backwards-incompatible, I'm going to give it some time before acting. In the meantime, I'd like to close this specific Issue because any of the potential directions will be entirely different (re-think our default extensions entirely, remove the `yesodDefault*` functions, etc).

Thanks for reporting these issues, and sorry I inadvertently broke this behavior through that upgrade...
