### ISSUE TITLE
Can we denote type safe URLs using markdown?

### ISSUE THREAD

**Issue by pythonissam** [pbrisbin/yesod-markdown#64]
Is this possible?

**Comment by pbrisbin** [comment]
Hmm, not easily I think.

This library is just a small wrapper over pandoc, which handles the Markdown -> HTML. It may be possible to write and inject a pandoc macro to transform urls, or you could preprocess with shakespeare (our Markdown type just a Text newtype). I could see the former as provided by this library, but I also see that as the less feasible. The latter would be something you could do in your own code.

I'm going to close for now, since I don't intend to support this any time soon. If a PR is opened in this area though, I would happily review.
